# Generated by Django 3.1.4 on 2020-12-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('stripe_id', models.CharField(max_length=70)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
