# Generated by Django 3.1.4 on 2020-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_remove_customer_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='harbor_login',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stripe_id',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
